# Stack configuration file:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The resolver determines which packages are used to resolve the dependencies
# in the Cabal build file.
# https://www.stackage.org/lts-8.12
resolver: lts-8.12
